SM.spawn=function(g,type,x,y,group){const [w,h]=type==='brute'?[56,70]:type==='sentry'?[38,42]:[40,30];let e={type,x,y:y-h,w,h,hp:SM.C.enemyHP[type],maxHp:SM.C.enemyHP[type],vx:0,vy:0,face:-1,state:'patrol',timer:.6,flash:0,origin:x,group,drop:0};g.enemies.push(e);return e};
SM.enemyShot=function(g,e,angle,speed=270,damage=9){g.projectiles.push({x:e.x+e.w/2,y:e.y+e.h/2,w:12,h:12,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:4,damage,enemy:true})};
SM.updateEnemies=function(g,dt){for(const e of g.enemies){if(e.hp<=0)continue;e.flash=Math.max(0,e.flash-dt);let p=g.player,dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy);e.timer-=dt;const dir=Math.sign(dx)||1;
if(e.type==='crawler'){if(e.state==='patrol'||e.state==='pursue'){e.state=dist<340?'pursue':'patrol';if(e.state==='pursue')e.face=dir;else if(Math.abs(e.x-e.origin)>100)e.face=e.x>e.origin?-1:1;e.vx=e.face*(e.state==='pursue'?100:42);let foot={x:e.x+e.w/2+e.face*27,y:e.y+e.h+5,w:3,h:12};if(!SM.solids(g).some(s=>SM.overlap(foot,s))&&e.grounded){e.vx=0;e.face*=-1}if(dist<100){e.state='attack';e.timer=.55;e.vx=0}}else if(e.state==='attack'&&e.timer<=0){if(dist<90)p.hurt(g,10,dir);e.state='cooldown';e.timer=.85}else if(e.state==='cooldown'){e.vx=0;if(e.timer<=0)e.state='pursue'}
}else if(e.type==='sentry'){e.face=dir;e.vx=0;if(e.state==='patrol'&&dist<560){e.state='attack';e.timer=1.05}if(e.state==='attack'&&e.timer<=0){let angle=Math.atan2(p.y+22-e.y-20,p.x+17-e.x-19);for(let a of [-.12,0,.12])SM.enemyShot(g,e,angle+a);e.state='cooldown';e.timer=1.9;g.audio.tone(300,.12,'sawtooth',.015,100)}else if(e.state==='cooldown'&&e.timer<=0)e.state='patrol';
}else{e.face=dir;if(e.state==='patrol'||e.state==='pursue'){e.vx=dist<460?dir*48:0;e.state='pursue';if(dist<155){e.state='attack';e.timer=1.05;e.vx=0}}else if(e.state==='attack'&&e.timer<=0){g.shake=5;for(const sign of [-1,1])g.projectiles.push({x:e.x+e.w/2,y:830,w:35,h:20,vx:sign*240,vy:0,life:.7,enemy:true,damage:18,shock:true});e.state='cooldown';e.timer=1.7;g.spark(e.x+25,845,'#ffc375',20)}else if(e.state==='cooldown'&&e.timer<=0)e.state='pursue'}
if(e.type!=='sentry'){e.vy+=SM.C.gravity*dt;SM.moveBody(g,e,dt);if(e.y>1000){e.hp=0;g.kills++}}if(SM.overlap(e,p)&&e.state!=='attack')p.hurt(g,SM.C.enemyDamage[e.type],dir);
}};
SM.makeBoss=()=>({x:6120,y:595,w:200,h:235,hp:SM.C.bossHealth,maxHp:SM.C.bossHealth,active:false,dead:false,phase:1,state:'idle',timer:1,pattern:0,flash:0});
SM.damageBoss=function(g,n){let b=g.boss;if(!b.active||b.dead)return;if(b.state!=='exposed'){g.spark(b.x,b.y+105,'#b5d1ce',3);return}b.hp-=n;b.flash=.12;g.player.torque=SM.clamp(g.player.torque+n*.1,0,100);g.spark(b.x+65,b.y+100,'#ffa357',8);if(b.hp<=0){b.hp=0;b.dead=true;b.active=false;g.extraction=SM.C.extractionTime;g.shake=18;g.kills++;g.spark(b.x+90,b.y+100,'#ffae50',100);g.toast('OVERSEER CORE COLLAPSING · REACH EXTRACTION');g.audio.tone(150,.9,'sawtooth',.07,20)}};
SM.updateBoss=function(g,dt){let b=g.boss,p=g.player;if(!b.active||b.dead)return;b.flash-=dt;b.phase=b.hp<=b.maxHp*.5?2:1;b.timer-=dt;if(b.state==='idle'){b.state=['rivets','sweep','summon'][b.pattern++%3];b.timer=b.phase===2?.85:1.2;g.toast(b.state==='sweep'?'ARM SWEEP · JUMP!':b.state==='rivets'?'MOLTEN RIVETS · KEEP MOVING':'ASSEMBLY DRONE INBOUND',1.1)}else if(b.state!=='exposed'&&b.timer<=0){if(b.state==='rivets'){const a=Math.atan2(p.y-b.y-70,p.x-b.x);for(let j=-2;j<=2;j++)SM.enemyShot(g,b,a+j*.16,b.phase===2?310:240,12);if(b.phase===2)for(let k=0;k<10;k++)SM.enemyShot(g,b,k*Math.PI/5+g.time,210,10)}if(b.state==='sweep'){g.projectiles.push({x:b.x-40,y:800,w:120,h:45,vx:-440,vy:0,life:1.8,enemy:true,damage:20,arm:true});g.shake=6}if(b.state==='summon')SM.spawn(g,'crawler',5730,850,'boss');b.state='exposed';b.timer=b.phase===2?1.7:2.5;g.toast('PROCESSOR EXPOSED · ATTACK',1.2)}else if(b.state==='exposed'&&b.timer<=0){b.state='idle';b.timer=.2}if(b.phase===2){if(p.grounded)p.x+=Math.sin(g.time*.5)>0?dt*65:-dt*65;let side=Math.floor(g.time/3)%2;let x=side?5800:5350;if(g.time%3>1.6&&SM.overlap(p,{x,y:838,w:260,h:12}))p.hurt(g,12,1)}};
