SM.Input=class{constructor(){this.keys=new Set;this.prev=new Set;addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.code==='Escape'&&!e.repeat)SM.game.pause()});addEventListener('keyup',e=>this.keys.delete(e.code));const canvas=document.getElementById('game');canvas.addEventListener('mousedown',e=>{this.keys.add('Mouse'+e.button);e.preventDefault()});addEventListener('mouseup',e=>this.keys.delete('Mouse'+e.button));canvas.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('blur',()=>{this.keys.clear();if(SM.game?.state==='playing')SM.game.pause()})}down(...keys){return keys.some(k=>this.keys.has(k))}pressed(...keys){return keys.some(k=>this.keys.has(k)&&!this.prev.has(k))}released(...keys){return keys.some(k=>!this.keys.has(k)&&this.prev.has(k))}end(){this.prev=new Set(this.keys)}};
SM.Game=class{constructor(){this.audio=new SM.Audio;this.input=new SM.Input;this.renderer=new SM.Render(document.getElementById('game'));this.intro=document.getElementById('overlay').innerHTML;this.reset();this.state='title';document.getElementById('start').onclick=()=>this.start();document.getElementById('pause').onclick=()=>this.pause();document.getElementById('sound').onclick=()=>{this.audio.enabled=!this.audio.enabled;document.getElementById('sound').textContent=this.audio.enabled?'SOUND ON':'SOUND OFF'};let last=performance.now();const frame=now=>{let dt=Math.min((now-last)/1000,.033);last=now;if(this.state==='playing')this.update(dt);else if(this.state==='title')this.time+=dt;this.renderer.draw(this);this.hud();this.input.end();requestAnimationFrame(frame)};requestAnimationFrame(frame)}
reset(){this.level=SM.makeLevel();this.player=new SM.Player;this.enemies=[];this.projectiles=[];this.particles=[];this.debris=[];this.boss=SM.makeBoss();this.time=0;this.elapsed=0;this.kills=0;this.damageTaken=0;this.lastDebris=-1;this.shake=0;this.hitstop=0;this.camera={x:0,y:370};this.toastTime=0;SM.setupProgress(this);this.saveCheckpoint()}
start(){this.audio.init();this.reset();this.state='playing';document.getElementById('overlay').style.display='none';this.toast('HELIX ASSEMBLY COMPLEX · MAINTENANCE BREACH',3)}
saveCheckpoint(){this.saved=JSON.stringify({level:this.level,enemies:this.enemies,modules:[...this.modules],encounters:this.encounters,checkpoint:this.checkpoint,checkpointIndex:this.checkpointIndex,kills:this.kills,pickups:this.pickups,lockdown:this.lockdown})}
restore(){let elapsed=this.elapsed,damage=this.damageTaken;const saved=this.saved;this.reset();let s=JSON.parse(saved);Object.assign(this,s);this.modules=new Set(s.modules);this.player=new SM.Player(s.checkpoint.x,s.checkpoint.y);this.player.hp=100;this.player.torque=60;this.boss=SM.makeBoss();this.elapsed=elapsed;this.damageTaken=damage;this.saved=saved;this.camera.x=SM.clamp(this.player.x-380,0,5980);this.camera.y=SM.clamp(this.player.y-350,0,370);this.state='playing';document.getElementById('overlay').style.display='none';this.input.keys.clear()}
update(dt){if(this.hitstop>0){this.hitstop-=dt;return}this.time+=dt;this.elapsed+=dt;this.shake=Math.max(0,this.shake-dt*25);this.toastTime-=dt;for(const lift of this.level.moving){let next=lift.baseY-Math.sin(this.time*lift.speed)*lift.range;lift.dy=next-lift.y;lift.y=next}this.player.update(this,dt);if(this.state!=='playing')return;SM.updateEnemies(this,dt);SM.updateProjectiles(this,dt);SM.updatePickups(this,dt);SM.updateProgress(this,dt);SM.updateBoss(this,dt);for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=350*dt;p.life-=dt*1.6}this.particles=this.particles.filter(p=>p.life>0).slice(-700);let targetX=SM.clamp(this.player.x-500+this.player.face*95,0,SM.C.worldW-1120),targetY=SM.clamp(this.player.y-370,0,370);this.camera.x+=(targetX-this.camera.x)*(1-Math.exp(-dt*5));this.camera.y+=(targetY-this.camera.y)*(1-Math.exp(-dt*4));this.audio.update(dt)}
spark(x,y,color,count){for(let k=0;k<count;k++)this.particles.push({x,y,color,vx:(Math.random()-.5)*240,vy:(Math.random()-.7)*210,life:.4+Math.random()*.5,size:2+Math.random()*3})}
toast(s,duration=2.4){this.toastText=s;this.toastTime=duration}
pause(){if(this.state==='playing'){this.state='paused';this.showOverlay('SYSTEM PAUSED','Take a breath. The assembly line can wait.',true)}else if(this.state==='paused'){this.state='playing';document.getElementById('overlay').style.display='none'}}
showOverlay(title,body,paused=false){let o=document.getElementById('overlay');o.style.display='flex';o.innerHTML=`<div class="intro result"><div class="tag">HELIX / MISSION TELEMETRY</div><h1>${title}</h1><div class="stats">${body}</div><button class="primary" id="again">${paused?'RESUME MISSION':'RESTART MISSION'} ↗</button>${paused?'<button class="secondary" id="restartPaused">RESTART MISSION</button>':''}${!paused&&this.state==='defeat'?'<button class="secondary" id="checkpoint">RESTART CHECKPOINT</button>':''}<div class="fine">A/D MOVE · SPACE JUMP · SHIFT DASH · J FIRE / HOLD CHARGE · K DRILL · E REBOUND</div></div>`;document.getElementById('again').onclick=()=>paused?this.pause():this.start();let restartPaused=document.getElementById('restartPaused');if(restartPaused)restartPaused.onclick=()=>this.start();let check=document.getElementById('checkpoint');if(check)check.onclick=()=>this.restore()}
finish(won,reason){if(this.state!=='playing')return;this.state=won?'victory':'defeat';this.spark(this.player.x,this.player.y,won?'#90ffe1':'#ff9c63',60);let time=Math.floor(this.elapsed/60)+':'+String(Math.floor(this.elapsed%60)).padStart(2,'0');this.showOverlay(won?'MISSION COMPLETE':reason||'UNIT OFFLINE',`<p>${won?'The Overseer Core is silent. ScrewMan is clear.':'Your field telemetry is preserved at the last checkpoint.'}</p>ENEMIES DESTROYED &nbsp; ${this.kills}<br>CONTROL MODULES &nbsp; ${this.modules.size}/3<br>COMPLETION TIME &nbsp; ${time}<br>DAMAGE TAKEN &nbsp; ${this.damageTaken}`)}
hud(){const set=(id,t)=>document.getElementById(id).textContent=t,p=this.player;document.getElementById('hp').style.width=p.hp+'%';document.getElementById('torque').style.width=p.torque+'%';set('hpText',Math.ceil(p.hp));set('torqueText',Math.floor(p.torque));set('ammo',String(p.ammo).padStart(2,'0'));set('progress','Control Modules: '+this.modules.size+'/3');let area=p.x<600?'MAINTENANCE CHAMBER':p.x<1780?'CONVEYOR PRODUCTION FLOOR':p.x<3300?'VERTICAL REACTOR SHAFT':p.x<5140?'SECURITY TESTING ROOM':p.x<6500?'CENTRAL FOUNDRY':'EXTRACTION CHAMBER';set('area',area);set('objective',this.extraction!==null?'Objective: Reach Extraction · '+Math.ceil(this.extraction)+'s':this.boss.active?'Destroy ForgeMind Prime':this.modules.size===3?'Enter the Central Foundry':'Recover the encrypted control modules');set('wave',this.encounters.foundry.active?'Wave '+this.encounters.foundry.wave+'/3 · Lockdown '+Math.max(0,Math.ceil(20-this.lockdown))+'s':this.encounters.reactor.active?'Reactor group '+this.encounters.reactor.wave+'/2':'');set('toast',this.toastTime>0?this.toastText:'');set('footerStatus',this.state==='playing'?'LIVE TELEMETRY / '+area:this.state.toUpperCase());document.getElementById('bossHud').style.display=this.boss.active?'block':'none';document.getElementById('bossHp').style.width=(this.boss.hp/this.boss.maxHp*100)+'%';set('phase','PHASE 0'+this.boss.phase)}
};
SM.game=new SM.Game;
