// Original indexed sprites. Every character is one pixel, drawn at 2 world units.
SM.PixelArt = {
 palette: {'.':null,'X':'#101426','s':'#303b55','m':'#576b83','l':'#94b3be','w':'#e7f1cf','o':'#b9572a','a':'#f28c38','y':'#ffce69','c':'#359bba','b':'#67e6da','r':'#c94452','p':'#ff8366'},
 hero: [
 '........XXXXXX..........',
 '......XXllwwllXX........',
 '.....XllwwwwwwlmX.......',
 '.....XlaaaaaaaalX.......',
 '....XyyyyyyyyyyyyX......',
 '.....XXssssssssXX.......',
 '.....XmbbbbsbbbmX.......',
 '......XlsssssslX........',
 '...XXXXmmllllmmXXXX.....',
 '..XlaalXaaaaaaXlaalX....',
 '..XyaaaXossssaoXaalX....',
 '..XoaamXscbbcsXmaamX....',
 '..XmmmXXcbwwbcXXmmmXXXXX',
 '..XllmXXcbwwbcXllwwlyymX',
 '...XmmXXscbbcsXmmllmmywX',
 '...XssXXooooooXssmmmyymX',
 '....XX.XlaaaalX.XXXXXXXX',
 '.......XmmllmmX.........',
 '.......XXXXXXXX.........',
 ],
 crawler:[
 '.......XXXXXX.........',
 '.....XXmllllmXX.......',
 '...XXllmmmmmmllXX.....',
 '..XmmrrrppprrrmmmX....',
 '.XlllXssssssXlllllX...',
 '.XmmlXrpppprXlmmmlX...',
 '..XmmXssssssXmmmXX....',
 'XXXmmXXXXXXXXmmXXXX...',
 'XwlXmmllllllmmXlwX....',
 '.XwlXmmmmmmmmXlwX.....',
 '..XX.XXXXXXXX.XX......',
 ],
 sentry:[
 '.........XX..........',
 '........XyyX.........',
 '.......XooooX........',
 '....XXXmmmmmmXXX.....',
 '..XXllmllllllmllXX...',
 '.XlllXXssssssXXlllX..',
 '.XlmXssrrrrrrssXmlX..',
 'XlmXssrpppppprssXmlX.',
 'XlmXsrpyyyypprsXmlmX.',
 'XlmXsrpywwypprsXmlmX.',
 'XlmXsrpyyyypprsXmlmX.',
 '.XlmXsrpppprsXlmX....',
 '..XllXssrrssXllX.....',
 '...XXllssssllXX......',
 '.....XXmmmmXX........',
 '.......XccX..........',
 '.......XbbX..........',
 '........ww...........',
 ],
 brute:[
 '.........XXXXXXXX...........',
 '........XmllllllmX..........',
 '.......XllwwwwlllmX.........',
 '.......XssssssssssX.........',
 '.......XrpprrpprrpX.........',
 '..XXXXXXssssssssssXXXXXX....',
 '.XlwwllXmmmmmmmmmmXllwwlX...',
 'XllaaalXoaaaaaaaaoXlaaallX..',
 'XlaaaamXassssssssaXmaaaalX..',
 'XmaaaamXscbbbbbbcsXmaaaamX..',
 '.XmmmXXscbwwwwwwbcsXXmmmX...',
 '.XlllXXscbwwyywwbcsXXlllX...',
 'XlwwlmXscbwwwwwwbcsXmlwwlX..',
 'XllmlmXXscbbbbbbcsXXmlmllX..',
 'XlmmmlXXassssssssaXXlmmmlX..',
 '.XmmmX.XooooaaaaoX..XmmmX...',
 '..XXX..XllllmmlllX...XXX....',
 '.......XXXXXXXXXX..........',
 ],
 draw(ctx, sprite, x,y, {flip=false,flash=false,scale=2}={}) {
   const width=Math.max(...sprite.map(row=>row.length));
   for(let row=0;row<sprite.length;row++) for(let col=0;col<sprite[row].length;col++) {
     const key=sprite[row][col],color=this.palette[key];if(!color)continue;
     ctx.fillStyle=flash&&key!=='X'?'#fff4c4':color;
     ctx.fillRect(Math.round(x/2)*2+(flip?width-1-col:col)*scale,Math.round(y/2)*2+row*scale,scale,scale);
   }
 }
};
