SM.setupProgress=function(g){g.modules=new Set();g.encounters={maintenance:{active:true,done:false,wave:1},reactor:{active:false,done:false,wave:0},foundry:{active:false,done:false,wave:0}};for(const x of [650,1040,1430])SM.spawn(g,'crawler',x,850,'maintenance');g.pickups=[{x:520,y:705,w:18,h:18,type:'health'},{x:1220,y:705,w:18,h:18,type:'ammo'},{x:2430,y:490,w:18,h:18,type:'health'},{x:3380,y:820,w:18,h:18,type:'health'},{x:5310,y:820,w:18,h:18,type:'health'},{x:5400,y:820,w:18,h:18,type:'ammo'}];g.checkpoint={...g.level.checkpoints[0]};g.checkpointIndex=0;g.extraction=null;g.lockdown=0};
SM.updateProgress=function(g,dt){let p=g.player,E=g.encounters;const alive=group=>g.enemies.some(e=>e.hp>0&&e.group===group);if(!E.maintenance.done&&!alive('maintenance')){E.maintenance.done=true;g.toast('BREACH CLEARED · RECOVER CONTROL MODULE 01')}
if(p.x>1790&&!E.reactor.active&&!E.reactor.done){E.reactor.active=true;E.reactor.wave=1;SM.spawn(g,'sentry',2350,460,'reactor');SM.spawn(g,'crawler',2490,850,'reactor');g.toast('REACTOR LOCKDOWN · GROUP 1 / 2')}
if(E.reactor.active&&!alive('reactor')){if(E.reactor.wave===1){E.reactor.wave=2;SM.spawn(g,'sentry',2940,430,'reactor');SM.spawn(g,'crawler',2680,850,'reactor');g.toast('REACTOR LOCKDOWN · GROUP 2 / 2')}else{E.reactor.done=true;E.reactor.active=false;g.toast('REACTOR STABILIZED · RECOVER MODULE 02')}}
if(p.x>3490&&!E.foundry.active&&!E.foundry.done){E.foundry.active=true;E.foundry.wave=0;g.lockdown=0}
if(E.foundry.active){g.lockdown+=dt;if(!alive('foundry')){if(E.foundry.wave<3){let wave=SM.C.waves[E.foundry.wave++];wave.forEach((type,k)=>SM.spawn(g,type,3920+k*240, type==='sentry'?710:850,'foundry'));g.toast('SECURITY LOCKDOWN · WAVE '+E.foundry.wave+' / 3')}else if(g.lockdown>=20){E.foundry.done=true;E.foundry.active=false;g.toast('LOCKDOWN CLEARED · RECOVER MODULE 03')}}}
for(const m of g.level.modules){let available=m.id===0?E.maintenance.done:m.id===1?true:E.foundry.done;if(available&&!g.modules.has(m.id)&&SM.overlap({x:m.x-12,y:m.y-12,w:52,h:56},p)){g.modules.add(m.id);g.audio.tone(400,.4,'sine',.05,1200);g.spark(m.x+14,m.y+16,'#7affd6',35);g.toast('CONTROL MODULE 0'+(m.id+1)+' RECOVERED');}}
const idx=p.x>5190?3:p.x>3340?2:p.x>1780?1:0;if(idx>g.checkpointIndex){g.checkpointIndex=idx;g.checkpoint={...g.level.checkpoints[idx]};p.hp=Math.max(p.hp,75);p.torque=Math.max(p.torque,40);p.ammo=Math.max(p.ammo,6);g.saveCheckpoint();g.toast('CHECKPOINT SYNCED · INTEGRITY RESTORED')}
if(p.x>5350&&!g.boss.active&&!g.boss.dead){g.boss.active=true;g.boss.state='idle';g.boss.timer=1;g.toast('FORGEMIND PRIME · CENTRAL FOUNDRY')}
if(g.boss.active&&p.x<5180)p.x=5180;
for(const h of g.level.hazards){let on=(g.time+(h.x%7))%3.5>1.6;if(on&&SM.overlap(p,{...h,y:h.type==='steam'?h.y-70:h.y,h:h.type==='steam'?80:h.h}))p.hurt(g,12,-p.face)}
if(p.x>3000&&p.x<4800&&Math.floor(g.time/4)>g.lastDebris){g.lastDebris=Math.floor(g.time/4);g.debris.push({x:p.x+100,y:p.y-300,w:20,h:28,vy:0,warning:.8})}for(const d of g.debris){d.warning-=dt;if(d.warning<=0){d.vy+=900*dt;d.y+=d.vy*dt;if(SM.overlap(d,p)){p.hurt(g,12,1);d.y=1100}}}g.debris=g.debris.filter(d=>d.y<1000);
if(g.extraction!==null){g.extraction-=dt;if(p.x>6880)g.finish(true);else if(g.extraction<=0)g.finish(false,'EXTRACTION WINDOW LOST')}
};
