const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map;const ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});
const document={getElementById(id){if(!elements.has(id))elements.set(id,{innerHTML:'',style:{},addEventListener(){},getContext:()=>ctx});return elements.get(id)}};
const env={window:{},document,addEventListener(){},requestAnimationFrame(){},performance:{now:()=>0},console,Math,Set};vm.createContext(env);for(const name of ['config','audio','level','player','combat','enemies','progression','pixel-art','pixel-font','render','game'])vm.runInContext(fs.readFileSync(__dirname+'/js/'+name+'.js','utf8'),env,{filename:name+'.js'});const S=env.window.SM,g=S.game;let passed=0;function test(name,fn){g.reset();g.state='playing';fn();console.log('PASS '+name);passed++}function tick(n,keys=[]){g.input.keys=new Set(keys);for(let k=0;k<n;k++){g.update(1/60);g.input.end()}}
test('Run, crouch, dash, variable jump, landing and wall collision',()=>{tick(60,['KeyD']);assert(g.player.x>300);tick(1,['KeyS']);assert.equal(g.player.h,34);tick(1,[]);assert.equal(g.player.h,54);tick(1,['ShiftLeft']);assert(g.player.dash>0);tick(40,[]);tick(1,['Space']);assert(g.player.vy<0);tick(1,[]);assert(g.player.vy>=-220);tick(60,[]);assert(g.player.grounded);g.player.x=1700;tick(90,['KeyD']);assert(g.player.x+g.player.w<=1740);assert(g.player.y+g.player.h<=850)});
test('Moving platform carry and designated platform drop',()=>{let s=g.level.moving[0];g.player.x=s.x+20;g.player.y=s.y-54;g.player.grounded=true;g.player.platform=s;tick(10);assert(Math.abs(g.player.y+54-s.y)<3);tick(1,['KeyS','Space']);assert(g.player.drop>0);tick(12,['KeyS']);assert(g.player.y+g.player.h>s.y)});
test('Quick bolts damage every enemy type through projectile collision',()=>{for(const type of ['crawler','sentry','brute']){g.enemies=[];g.player.x=200;g.player.y=796;const e=S.spawn(g,type,270,850,'test');if(type==='sentry')e.y=810;const hp=e.hp;S.shoot(g,false,false);for(let j=0;j<10;j++)S.updateProjectiles(g,1/60);assert(e.hp<hp,type)}});
test('Charged spiral spends Torque and increases damage',()=>{g.player.torque=60;S.shoot(g,true,false);assert.equal(g.player.torque,40);assert(g.projectiles[0].damage>S.C.boltDamage)});
test('Drill damages enemies and breaks machinery',()=>{g.player.x=1010;g.player.y=796;g.player.torque=100;g.input.keys=new Set(['KeyK']);let e=S.spawn(g,'brute',1055,850,'test');const hp=e.hp;for(let j=0;j<50;j++)S.playerCombat(g,1/60);assert(g.level.machines[0].hp<=0);assert(e.hp<hp);assert(g.player.torque<100)});
test('Rebound reflects once from solid wall',()=>{g.player.x=1680;g.player.y=796;S.shoot(g,false,true);for(let j=0;j<12;j++)S.updateProjectiles(g,1/60);assert(g.projectiles.some(b=>b.bounces===1&&b.vx<0))});
test('Enemy telegraph, pursuit and attack damage; invulnerability',()=>{g.enemies=[];g.player.x=300;g.player.y=796;const e=S.spawn(g,'crawler',370,850,'test');S.updateEnemies(g,.01);assert.equal(e.state,'attack');assert.equal(g.player.hp,100);for(let j=0;j<36;j++)S.updateEnemies(g,1/60);assert(g.player.hp<100);let hp=g.player.hp;g.player.hurt(g,30,1);assert.equal(g.player.hp,hp)});
test('Pickups restore health, Torque, ammunition',()=>{g.player.hp=30;g.player.torque=0;g.player.ammo=0;g.pickups=['health','scrap','ammo'].map(type=>({x:g.player.x,y:g.player.y,w:18,h:18,type}));S.updatePickups(g,.01);assert.equal(g.player.hp,58);assert.equal(g.player.torque,24);assert.equal(g.player.ammo,4)});
test('All modules increment progress and gate requires three',()=>{g.encounters.maintenance.done=true;g.encounters.foundry.done=true;for(const m of g.level.modules){g.player.x=m.x;g.player.y=m.y;S.updateProgress(g,0)}assert.equal(g.modules.size,3);assert(S.gateOpen(g,g.level.gates[2]));g.modules.delete(1);assert(!S.gateOpen(g,g.level.gates[2]))});
test('Foundry waves never advance with living enemies',()=>{g.player.x=3600;S.updateProgress(g,.1);assert.equal(g.encounters.foundry.wave,1);S.updateProgress(g,10);assert.equal(g.encounters.foundry.wave,1);for(let wave=2;wave<=3;wave++){g.enemies.forEach(e=>e.hp=0);S.updateProgress(g,.1);assert.equal(g.encounters.foundry.wave,wave)}g.enemies.forEach(e=>e.hp=0);S.updateProgress(g,20);assert(g.encounters.foundry.done)});
test('Boss shield, phase two, defeat, extraction and victory',()=>{g.boss.active=true;g.boss.state='rivets';let hp=g.boss.hp;S.damageBoss(g,40);assert.equal(g.boss.hp,hp);g.boss.state='exposed';S.damageBoss(g,hp*.55);S.updateBoss(g,.01);assert.equal(g.boss.phase,2);g.boss.state='exposed';S.damageBoss(g,1000);assert(g.boss.dead);assert.equal(g.extraction,S.C.extractionTime);g.player.x=6900;S.updateProgress(g,.1);assert.equal(g.state,'victory')});
test('Health and countdown defeat, checkpoint restore, full restart',()=>{g.player.hurt(g,100,1);assert.equal(g.state,'defeat');g.restore();assert.equal(g.player.hp,100);assert.equal(g.state,'playing');g.extraction=.01;S.updateProgress(g,.1);assert.equal(g.state,'defeat');g.reset();assert.equal(g.modules.size,0);assert.equal(g.enemies.length,3);assert.equal(g.encounters.foundry.wave,0);assert.equal(g.player.hp,100);assert.equal(g.extraction,null)});
test('Camera bounds and renderer smoke test across all rooms and boss states',()=>{for(const x of [0,1900,2700,3800,5500,6900]){g.player.x=x;g.player.y=400;tick(1);assert(g.camera.x>=0&&g.camera.x<=5980);assert(g.camera.y>=0&&g.camera.y<=370);g.renderer.draw(g)}for(const state of ['rivets','sweep','summon','exposed']){g.boss.state=state;g.boss.active=true;g.boss.phase=2;g.renderer.draw(g)}});
test('Reactor route platform jumps are physically reachable',()=>{g.enemies=[];for(const [x,y,targetX,targetY] of [[1950,745,2060,640],[2190,640,2320,520],[2440,520,2580,430]]){g.player=new S.Player(x,y-54);g.player.grounded=true;g.player.coyote=.1;g.input.prev=new Set();let landed=false;for(let k=0;k<65;k++){let keys=['Space'];if(g.player.x<targetX+15)keys.push('KeyD');g.input.keys=new Set(keys);g.player.update(g,1/60);g.input.end();if(g.player.grounded&&Math.abs(g.player.y+g.player.h-targetY)<2){landed=true;break}}assert(landed,`Could not reach platform at ${targetX},${targetY}`)}});
console.log(`${passed} system checks passed. These are isolated simulations, not a full player playthrough.`);
